# stage 1
FROM node:latest as node
build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run buil --prod
expose 3000
cmd ["npm","run","start"]
# stage 2
FROM nginx:alpine
COPY --from=node /app/dist/angular-app /usr/share/nginx/html
